version: "3.7"

services:
  dbt-example-postgresql:
    image: postgres:11
    container_name: dbt-example-postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "dbt-example"
      POSTGRES_PASSWORD: "dbt-example"
      POSTGRES_DB: "dbt-example"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
    name: postgres
