version: "3.7"

services:
  dbt_example_postgresql:
    image: postgres:11
    container_name: dbt_example_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "dagster_postgres"
      POSTGRES_PASSWORD: "dagster_postgres"
      POSTGRES_DB: "dagster_postgres"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
    name: postgres
