contact_links:

  - name: Ask a question, get help, or share ideas ðŸ’¡
    url: https://github.com/dagster-io/dagster/discussions/category_choices
    about: Discuss everything

  - name: Add your company logo or write posts ðŸŽ¨
    url: https://github.com/dagster-io/dagster-website
    about: Visit dagster.io repo