dependencies:
  - name: postgresql
    version: 8.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.deployInK8s
  - name: rabbitmq
    version: 6.16.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq.enabled