{{- if .Values.userDeployments.enabled }}
{{ range $deployment := .Values.userDeployments.deployments }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name }}
  labels:
    {{- include "dagster.labels" $ | nindent 4 }}
    component: user-deployments
spec:
  type: "ClusterIP"
  ports:
    - port: 3030
      protocol: TCP
      name: http
  selector:
    {{- include "dagster.selectorLabels" $ | nindent 4 }}
    component: user-deployments
---
{{ end }}
{{ end }}