---
dependencies:
  - name: postgresql
    version: 8.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: rabbitmq
    version: 6.16.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq.enabled
  - name: redis
    version: 1.0.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
