{{- if .Values.global.postgresqlConnectionString.generatePostgresqlConnectionStringSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.postgresqlConnectionString.postgresqlConnectionStringSecretName | quote }}
  labels:
    app: "{{ template "dagster.name" . }}"
    chart: "{{ template "dagster.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  postgresql-connection-string: {{ .Values.global.postgresqlConnectionString.connectionString | b64enc | quote }}
{{- end }}
