{{- if .Values.userDeployments.enabled }}
{{ range $deployment := .Values.userDeployments.deployments }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name }}
  labels:
    {{- include "dagster.labels" $ | nindent 4 }}
    component: user-deployments
    deployment: {{ $deployment.name }}
  annotations:
    {{- if $deployment.service.annotations }}
    {{ toYaml $deployment.service.annotations | trim | indent 4 }}
    {{- end }}
spec:
  type: {{ $deployment.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $deployment.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "dagster.selectorLabels" $ | nindent 4 }}
    component: user-deployments
    deployment: {{ $deployment.name }}
---
{{ end }}
{{ end }}